### ISSUE TITLE
Bower Main Should Point At Non-Minified Version

### ISSUE THREAD

**Issue by mtpultz** [angulartics/angulartics-mixpanel#22]
Bower main is for automated tooling and shouldn't be the minified version since the tooling is typically set on --production to minify all dependencies, but as is the minified file will be reminified.

Incidentally I only noticed this since there is an issue with the minified version on master, which I'm using to get this callback #18.  Appears to be related to eventTrack's properties parameter being undefined, but there's no issue using the non-minified version.  Might be related to PR #19.

**Comment by mtpultz** [comment]
I updated bower.json and pushed a PR #23

**Comment by timelf123** [comment]
merged, will cut a release asap

**Comment by mtpultz** [comment]
Thanks @timelf123 will look for the release

**Comment by mtpultz** [comment]
Hi @timelf123 sorry to bug you.  Is it possible to cut a minor release that includes these changes so we don't have to work off master in case of any breaking changes introduced during development.

**Comment by timelf123** [comment]
Built and pushed, sorry for delay
