### ISSUE TITLE
TypeError: $analyticsProvider.registerIncrementProperty is not a function

### ISSUE THREAD

**Issue by nevcos** [angulartics/angulartics-mixpanel#25]
Giving this error:
```
TypeError: $analyticsProvider.registerIncrementProperty is not a function
```

Using:
- angulartics version 1.0.3
- angulartics-mixpanel version 0.1.3

From the angulartics code, doesn't seem to be any `registerIncrementProperty` function in any version.

angulartics-mixpanel version 0.1.2 works as expected

**Comment by Edorka** [comment]
+1, we are downgrading to 0.1.2 thanks @nevcos

**Comment by marcelchastain** [comment]
@nevcos @Edorka 
support for `incrementProperty` was added in angulartics 1.1.0; manually updating your dependencies should fix the issue.

```bash
bower install angulartics#1.4.0 --save
```

Submitted PR #32 to fix it permanently.

**Comment by timelf123** [comment]
https://github.com/angulartics/angulartics-mixpanel/commit/6e7aed1e06a5ea853df640ea38528ef9ec0c9461 ty
