### ISSUE TITLE
Any docs on setting up user identity? 

### ISSUE THREAD

**Issue by husseiny** [angulartics/angulartics-mixpanel#8]
First off thanks for writing and sharing this! Extremely helpful and saved us a lot of time. Is there any documentation around on the best way to set up Mixpanel user identity?

**Comment by martinbavio** [comment]
I'm looking forward to this too. +1

**Comment by jasonbodily** [comment]
If you read the source code, setUsername is correlated with mixpanel.identify. So in your app, calling $analytics.setUsername('etc') will take care of identify. Follow the instructions here for more on mixpanel implementation: https://mixpanel.com/help/questions/articles/how-should-i-handle-my-user-identity-with-the-mixpanel-javascript-library

Is that what you were looking for?

**Comment by husseiny** [comment]
Thanks @jasonbodily I am going to take a look!

**Comment by timelf123** [comment]
Please reopen if you still are experiencing issues
